/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */ 
package main;

import entity.convertclasstoobject;
import entity.pasien;
import entity.dokter;
import entity.pegawai;
import entity.laporanpenyakit;
import entity.pelaporanugd;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hafizh
 */
public class MainFormStore extends javax.swing.JFrame {
 String tanggal1,tanggal2,tanggal3,tanggal4; 

    /**
     * Creates new form MainFormStore
     */
    //DefaultTableModel model;
    
    public MainFormStore() {
        initComponents();
        setDatapasien();
        setDatadokter();
        setDatapegawai();
        setDatalaporanpenyakit();
        setDatapelaporan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setDatapasien(){
        convertclasstoobject cbto = new convertclasstoobject();
        String[][] datapasien = cbto.getAllpasien();
        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            datapasien,
            new String [] {
                "KTP", "nama Pasien", "alamat Pasien", "nohp Pasien", "ttl pasien", "gejala pasien"
            }
        ));
        jScrollPane2.setViewportView(tblpasien);
    }   
    private void setDatalaporanpenyakit(){
        convertclasstoobject cbto = new convertclasstoobject();
        String[][] datalaporanpenyakit = cbto.getAlllaporanpenyakit();
        tbllaporanpenyakit.setModel(new javax.swing.table.DefaultTableModel(
            datalaporanpenyakit,
            new String [] {
                "id laporan", "ktp", "id dokter", "penyakit pasien", "obat"
            }
        ));
        jScrollPane5.setViewportView(tbllaporanpenyakit);
    }   
    private void setDatapelaporan(){
        convertclasstoobject cbto = new convertclasstoobject();
        String[][] datapelaporanugd = cbto.getAllpelaporanugd();
        tblpelaporan.setModel(new javax.swing.table.DefaultTableModel(
            datapelaporanugd,
            new String [] {
                "id pelaporan", "id laporan penyakit", "id pegawai", "tanggal pelaporan", "status"
            }
        ));
        jScrollPane7.setViewportView(tblpelaporan);
    }   
    
    private void setDatadokter(){
        convertclasstoobject ccto = new convertclasstoobject();
        String[][] datadokter = ccto.getAlldokter();
        tbldokter.setModel(new javax.swing.table.DefaultTableModel(
            datadokter,
            new String [] {
                "Id Dokter", "nama Dokter", "alamat Dokter","nohp dokter", "ttl dokter"
            }
        ));
        jScrollPane3.setViewportView(tbldokter);
    }  
    
    private void setDatapegawai(){
        convertclasstoobject cpto = new convertclasstoobject();
        String[][] datapegawai = cpto.getAllpegawai();
        tblpegawai.setModel(new javax.swing.table.DefaultTableModel(
            datapegawai,
            new String [] {
                "Id Pegawai", "nama Pegawai", "Alamat Pegawai", "nohp pegawai", "ttl pegawai"
            }
        ));
        jScrollPane4.setViewportView(tblpegawai);
    }  

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnpasien = new javax.swing.JButton();
        btndokter = new javax.swing.JButton();
        btnpegawai = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnldokter = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        iddokter = new javax.swing.JTextField();
        btnhapusd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbldokter = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namadokter = new javax.swing.JTextField();
        btncreated = new javax.swing.JButton();
        btnUpdated = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        alamatdokter = new javax.swing.JTextField();
        nohpdokter = new javax.swing.JTextField();
        dated = new com.toedter.calendar.JDateChooser();
        pnllaporan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        idlaporan = new javax.swing.JTextField();
        ktp = new javax.swing.JTextField();
        id_dokter = new javax.swing.JTextField();
        penyakit_pasien = new javax.swing.JTextField();
        obat = new javax.swing.JTextField();
        btncreatel = new javax.swing.JButton();
        btnupdatel = new javax.swing.JButton();
        btnhapusl = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbllaporanpenyakit = new javax.swing.JTable();
        pnlpegawai = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        alamatpegawai = new javax.swing.JTextField();
        btnUpdatepg = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblpegawai = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        namapegawai = new javax.swing.JTextField();
        btnUpdate5 = new javax.swing.JButton();
        btnsimpanpg = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        idpegawai = new javax.swing.JTextField();
        nohppegawai = new javax.swing.JTextField();
        datepgw = new com.toedter.calendar.JDateChooser();
        pnlpasien = new javax.swing.JPanel();
        pnlInputBuku = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idpasien = new javax.swing.JTextField();
        namapasien = new javax.swing.JTextField();
        gejalapasien = new javax.swing.JTextField();
        btnSimpanp = new javax.swing.JButton();
        btnHapusp = new javax.swing.JButton();
        btnUpdatep = new javax.swing.JButton();
        alamatpasien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nohppasien = new javax.swing.JTextField();
        datep = new com.toedter.calendar.JDateChooser();
        pnlTblBuku = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        pnlpelaporan = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblpelaporan = new javax.swing.JTable();
        makebtn = new javax.swing.JButton();
        btndeletepu = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        idpelaporan1 = new javax.swing.JTextField();
        idlaporan1 = new javax.swing.JTextField();
        idpegawai1 = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        status1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnpasien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ugdicon/pasien.png"))); // NOI18N
        btnpasien.setText("Data Pasien");
        btnpasien.setFocusable(false);
        btnpasien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpasien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpasienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnpasien);

        btndokter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ugdicon/dokter.png"))); // NOI18N
        btndokter.setText("Data Dokter");
        btndokter.setFocusable(false);
        btndokter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndokter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndokterActionPerformed(evt);
            }
        });
        jToolBar1.add(btndokter);

        btnpegawai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ugdicon/pegawai.png"))); // NOI18N
        btnpegawai.setText("Data Pegawai");
        btnpegawai.setFocusable(false);
        btnpegawai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpegawai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpegawaiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnpegawai);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ugdicon/exam.png"))); // NOI18N
        jButton3.setText("laporan penyakit");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ugdicon/analysis.png"))); // NOI18N
        jButton2.setText("Report");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ugdicon/exit.png"))); // NOI18N
        jButton1.setText("Log Out");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        pnlUtama.setLayout(new java.awt.CardLayout());

        jLabel7.setText("Input Data Dokter");

        iddokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddokterActionPerformed(evt);
            }
        });

        btnhapusd.setText("Delete");
        btnhapusd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusdActionPerformed(evt);
            }
        });

        tbldokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id Dokter", "nama Dokter", "alamat dokter", "nohp", "ttl"
            }
        ));
        tbldokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldokterMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbldokter);

        jLabel8.setText("Id_Dokter");

        jLabel9.setText("Nama Dokter");

        jLabel10.setText("Alamat Dokter");

        namadokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namadokterActionPerformed(evt);
            }
        });

        btncreated.setText("Create");
        btncreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatedActionPerformed(evt);
            }
        });

        btnUpdated.setText("Update");
        btnUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatedActionPerformed(evt);
            }
        });

        jLabel15.setText("TTL Dokter");

        jLabel16.setText("Nohp Dokter");

        alamatdokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatdokterActionPerformed(evt);
            }
        });

        nohpdokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpdokterActionPerformed(evt);
            }
        });

        dated.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datedPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnldokterLayout = new javax.swing.GroupLayout(pnldokter);
        pnldokter.setLayout(pnldokterLayout);
        pnldokterLayout.setHorizontalGroup(
            pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldokterLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namadokter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldokterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(105, 105, 105)
                        .addComponent(iddokter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnldokterLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alamatdokter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnldokterLayout.createSequentialGroup()
                        .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnldokterLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnldokterLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btncreated)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdated)
                                .addGap(60, 60, 60)))
                        .addComponent(btnhapusd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldokterLayout.createSequentialGroup()
                        .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nohpdokter, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(dated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnldokterLayout.setVerticalGroup(
            pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldokterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnldokterLayout.createSequentialGroup()
                        .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnldokterLayout.createSequentialGroup()
                                .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnldokterLayout.createSequentialGroup()
                                        .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnldokterLayout.createSequentialGroup()
                                                .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(iddokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel9))
                                            .addComponent(namadokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel10))
                                    .addComponent(alamatdokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel16))
                            .addComponent(nohpdokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15))
                    .addComponent(dated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnldokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncreated)
                    .addComponent(btnUpdated)
                    .addComponent(btnhapusd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnldokterLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlUtama.add(pnldokter, "carddokter");
        pnldokter.getAccessibleContext().setAccessibleName("");

        jLabel1.setText("id laporan");

        jLabel21.setText("input data laporan");

        jLabel22.setText("ktp");

        jLabel23.setText("id dokter");

        jLabel24.setText("penyakit pasien");

        jLabel25.setText("obat");

        btncreatel.setText("Create");
        btncreatel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatelActionPerformed(evt);
            }
        });

        btnupdatel.setText("Update");
        btnupdatel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatelActionPerformed(evt);
            }
        });

        btnhapusl.setText("Delete");
        btnhapusl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapuslActionPerformed(evt);
            }
        });

        tbllaporanpenyakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbllaporanpenyakit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllaporanpenyakitMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbllaporanpenyakit);

        javax.swing.GroupLayout pnllaporanLayout = new javax.swing.GroupLayout(pnllaporan);
        pnllaporan.setLayout(pnllaporanLayout);
        pnllaporanLayout.setHorizontalGroup(
            pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllaporanLayout.createSequentialGroup()
                .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnllaporanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(pnllaporanLayout.createSequentialGroup()
                                .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(39, 39, 39)
                                .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(obat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(idlaporan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ktp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(penyakit_pasien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_dokter)))))
                    .addGroup(pnllaporanLayout.createSequentialGroup()
                        .addComponent(btncreatel)
                        .addGap(34, 34, 34)
                        .addComponent(btnupdatel)
                        .addGap(40, 40, 40)
                        .addComponent(btnhapusl)))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnllaporanLayout.setVerticalGroup(
            pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnllaporanLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(33, 33, 33)
                        .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(idlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(ktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(id_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(penyakit_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncreatel)
                            .addComponent(btnupdatel)
                            .addComponent(btnhapusl))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pnlUtama.add(pnllaporan, "cardlaporan");
        pnllaporan.getAccessibleContext().setAccessibleDescription("");

        jLabel11.setText("Input Data Pegawai");

        alamatpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatpegawaiActionPerformed(evt);
            }
        });

        btnUpdatepg.setText("Update");
        btnUpdatepg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatepgActionPerformed(evt);
            }
        });

        tblpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id pegawai", "nama pegawai", "alamat Pegawai", "nohp pegawai", "ttl pegawai"
            }
        ));
        tblpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpegawaiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblpegawai);

        jLabel12.setText("id pegawai");

        jLabel13.setText("nama Pegawai");

        jLabel14.setText("Alamat Pegawai");

        namapegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapegawaiActionPerformed(evt);
            }
        });

        btnUpdate5.setText("Delete");
        btnUpdate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate5ActionPerformed(evt);
            }
        });

        btnsimpanpg.setText("Create");
        btnsimpanpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanpgActionPerformed(evt);
            }
        });

        jLabel17.setText("nohp Pegawai");

        jLabel18.setText("ttl pegawai");

        idpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpegawaiActionPerformed(evt);
            }
        });

        nohppegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohppegawaiActionPerformed(evt);
            }
        });

        datepgw.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datepgwPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlpegawaiLayout = new javax.swing.GroupLayout(pnlpegawai);
        pnlpegawai.setLayout(pnlpegawaiLayout);
        pnlpegawaiLayout.setHorizontalGroup(
            pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpegawaiLayout.createSequentialGroup()
                .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpegawaiLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnsimpanpg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdatepg)
                        .addGap(40, 40, 40)
                        .addComponent(btnUpdate5)
                        .addGap(47, 47, 47))
                    .addGroup(pnlpegawaiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpegawaiLayout.createSequentialGroup()
                        .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namapegawai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idpegawai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatpegawai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nohppegawai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datepgw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlpegawaiLayout.setVerticalGroup(
            pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpegawaiLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlpegawaiLayout.createSequentialGroup()
                                .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlpegawaiLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel12)
                                        .addGap(25, 25, 25)
                                        .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(namapegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlpegawaiLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(alamatpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nohppegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel18))
                            .addGroup(pnlpegawaiLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datepgw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(pnlpegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate5)
                            .addComponent(btnsimpanpg)
                            .addComponent(btnUpdatepg)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlpegawai, "cardpegawai");

        pnlInputBuku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Input Data Pasien");
        pnlInputBuku.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setText("KTP");
        pnlInputBuku.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setText("Nama pasien");
        pnlInputBuku.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setText("gejala pasien");
        pnlInputBuku.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        idpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpasienActionPerformed(evt);
            }
        });
        pnlInputBuku.add(idpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 180, -1));
        pnlInputBuku.add(namapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, -1));
        pnlInputBuku.add(gejalapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, 20));

        btnSimpanp.setText("Create");
        btnSimpanp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanpActionPerformed(evt);
            }
        });
        pnlInputBuku.add(btnSimpanp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnHapusp.setText("Delete");
        btnHapusp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapuspActionPerformed(evt);
            }
        });
        pnlInputBuku.add(btnHapusp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        btnUpdatep.setText("Update");
        btnUpdatep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatepActionPerformed(evt);
            }
        });
        pnlInputBuku.add(btnUpdatep, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));
        pnlInputBuku.add(alamatpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, -1));

        jLabel6.setText("alamat pasien");
        pnlInputBuku.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel19.setText("nohp pasien");
        pnlInputBuku.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel20.setText("ttl pasien");
        pnlInputBuku.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        pnlInputBuku.add(nohppasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 30));

        datep.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datepPropertyChange(evt);
            }
        });
        pnlInputBuku.add(datep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 170, -1));

        javax.swing.GroupLayout pnlTblBukuLayout = new javax.swing.GroupLayout(pnlTblBuku);
        pnlTblBuku.setLayout(pnlTblBukuLayout);
        pnlTblBukuLayout.setHorizontalGroup(
            pnlTblBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        pnlTblBukuLayout.setVerticalGroup(
            pnlTblBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ktp", "nama pasien", "alamat barang", "nohp pasien", "ttl pasien", "gejala pasien"
            }
        ));
        tblpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpasien);

        javax.swing.GroupLayout pnlpasienLayout = new javax.swing.GroupLayout(pnlpasien);
        pnlpasien.setLayout(pnlpasienLayout);
        pnlpasienLayout.setHorizontalGroup(
            pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTblBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlpasienLayout.setVerticalGroup(
            pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpasienLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlpasienLayout.createSequentialGroup()
                        .addComponent(pnlTblBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(pnlInputBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlUtama.add(pnlpasien, "cardpasien");
        pnlpasien.getAccessibleContext().setAccessibleName("");

        jScrollPane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane7MouseClicked(evt);
            }
        });

        tblpelaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblpelaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpelaporanMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblpelaporan);

        makebtn.setText("Make Report");
        makebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makebtnActionPerformed(evt);
            }
        });

        btndeletepu.setText("Delete");

        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlpelaporanLayout = new javax.swing.GroupLayout(pnlpelaporan);
        pnlpelaporan.setLayout(pnlpelaporanLayout);
        pnlpelaporanLayout.setHorizontalGroup(
            pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpelaporanLayout.createSequentialGroup()
                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(idpelaporan1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(idlaporan1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(idpegawai1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makebtn)
                    .addComponent(btndeletepu)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlpelaporanLayout.setVerticalGroup(
            pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpelaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                        .addComponent(makebtn)
                        .addGap(38, 38, 38)
                        .addComponent(btndeletepu)
                        .addGap(35, 35, 35)
                        .addComponent(jButton7)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)
                        .addGap(39, 39, 39)
                        .addComponent(jButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idpelaporan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idlaporan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idpegawai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlpelaporan, "cardpelaporan");
        pnlpelaporan.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpasienActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardpasien");
    }//GEN-LAST:event_btnpasienActionPerformed

    private void btndokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndokterActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "carddokter");
    }//GEN-LAST:event_btndokterActionPerformed

    private void btnpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpegawaiActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardpegawai");
    }//GEN-LAST:event_btnpegawaiActionPerformed

    private void btnSimpanpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanpActionPerformed
        String ktp = idpasien.getText();
        String nama_pasien = namapasien.getText();
        String alamat_pasien = alamatpasien.getText();
        String nohp_pasien = nohppasien.getText();
        String ttl_pasien = tanggal1;
        String gejala_pasien = gejalapasien.getText();
        entity.pasien pasien = new entity.pasien(ktp, nama_pasien, alamat_pasien, nohp_pasien, ttl_pasien, gejala_pasien);
        execute.execpasien eBook = new execute.execpasien();
        int hasil = eBook.insertpasien(pasien);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDatapasien();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }

    }//GEN-LAST:event_btnSimpanpActionPerformed

    private void btnHapuspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapuspActionPerformed
        String ktp = idpasien.getText();
        execute.execpasien eBook = new execute.execpasien();
        int hasil = eBook.deletepasien(ktp);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDatapasien();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }

    }//GEN-LAST:event_btnHapuspActionPerformed

    private void btnUpdatepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatepActionPerformed
        String ktp = idpasien.getText();
        String nama_pasien = namapasien.getText();
        String alamat_pasien = alamatpasien.getText();
        String nohp_pasien = nohppasien.getText();
        String ttl_pasien = tanggal1;
        String gejala_pasien = gejalapasien.getText();
        entity.pasien pasien = new entity.pasien(ktp, nama_pasien, alamat_pasien, nohp_pasien, ttl_pasien, gejala_pasien);
        execute.execpasien eBook = new execute.execpasien();
        int hasil = eBook.updatepasien(pasien);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDatapasien();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }

    }//GEN-LAST:event_btnUpdatepActionPerformed

    private void tblpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpasienMouseClicked
        int row = tblpasien.getSelectedRow();
        String ktp = tblpasien.getValueAt(row, 0).toString();
        String nama_pasien = tblpasien.getValueAt(row, 1).toString();
        String alamat_pasien = tblpasien.getValueAt(row, 2).toString();
        String nohp_pasien= tblpasien.getValueAt(row, 3).toString();
        String ttl_pasien= tblpasien.getValueAt(row, 4).toString();
        String gejala_pasien= tblpasien.getValueAt(row, 5).toString();
        idpasien.setText(ktp);
        namapasien.setText(nama_pasien);
        alamatpasien.setText(alamat_pasien);
        nohppasien.setText(nohp_pasien);
        datep.setDateFormatString(ttl_pasien);
        gejalapasien.setText(gejala_pasien);
        

    }//GEN-LAST:event_tblpasienMouseClicked

    private void idpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpasienActionPerformed

    private void iddokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddokterActionPerformed

    private void btnhapusdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusdActionPerformed
        String id_dokter = iddokter.getText();
        execute.execdokter eBook = new execute.execdokter();
        int hasil = eBook.deletedokter(id_dokter);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDatadokter();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnhapusdActionPerformed

    private void tbldokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldokterMouseClicked
        int row = tbldokter.getSelectedRow();
        String id_dokter = tbldokter.getValueAt(row, 0).toString();
        String nama_dokter = tbldokter.getValueAt(row, 1).toString();
        String alamat_dokter = tbldokter.getValueAt(row, 2).toString();
        String nohp_dokter = tbldokter.getValueAt(row, 3).toString();
        String ttl_dokter = tbldokter.getValueAt(row, 4).toString();
        iddokter.setText(id_dokter);
        namadokter.setText(nama_dokter);
        alamatdokter.setText(alamat_dokter);
        nohpdokter.setText(nohp_dokter);
        dated.setDateFormatString(ttl_dokter);
    }//GEN-LAST:event_tbldokterMouseClicked

    private void namadokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namadokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namadokterActionPerformed

    private void btncreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatedActionPerformed
        String id_dokter = iddokter.getText();        
        String nama_dokter= namadokter.getText();
        String alamat_dokter = alamatdokter.getText();
        String nohp_dokter = nohpdokter.getText();
        String ttl_dokter = tanggal2;
        entity.dokter dokter = new entity.dokter(id_dokter, nama_dokter, alamat_dokter, nohp_dokter, ttl_dokter);
        execute.execdokter eBook = new execute.execdokter();
        int hasil = eBook.insertdokter(dokter);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDatadokter();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }

            
    }//GEN-LAST:event_btncreatedActionPerformed

    private void btnUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatedActionPerformed
        String id_dokter = iddokter.getText();        
        String nama_dokter= namadokter.getText();
        String alamat_dokter = alamatdokter.getText();
        String nohp_dokter = nohpdokter.getText();
        String ttl_dokter = tanggal2;
        entity.dokter dokter = new entity.dokter(id_dokter, nama_dokter, alamat_dokter, ttl_dokter, nohp_dokter);
        execute.execdokter eBook = new execute.execdokter();
        int hasil = eBook.updatedokter(dokter);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDatadokter();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }

         
    }//GEN-LAST:event_btnUpdatedActionPerformed

    private void btnUpdatepgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatepgActionPerformed
        String id_pegawai = idpegawai.getText();        
        String nama_pegawai= namapegawai.getText();
        String alamat_pegawai = alamatpegawai.getText();
        String nohp_pegawai = nohppegawai.getText();
        String ttl_pegawai = tanggal3;
        entity.pegawai pegawai = new entity.pegawai(id_pegawai, nama_pegawai, ttl_pegawai, nohp_pegawai, alamat_pegawai);
        execute.execpegawai eBook = new execute.execpegawai();
        int hasil = eBook.updatepegawai(pegawai);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDatapegawai();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_btnUpdatepgActionPerformed

    private void tblpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpegawaiMouseClicked
        int row = tblpegawai.getSelectedRow();
        String id_pegawai = tblpegawai.getValueAt(row, 0).toString();
        String nama_pegawai = tblpegawai.getValueAt(row, 1).toString();
        String alamat_pegawai = tblpegawai.getValueAt(row, 2).toString();
        String nohp_pegawai = tblpegawai.getValueAt(row, 3).toString();
        String ttl_pegawai = tblpegawai.getValueAt(row, 4).toString();
        idpegawai.setText(id_pegawai);
        namapegawai.setText(nama_pegawai);
        alamatpegawai.setText(alamat_pegawai);
        nohppegawai.setText(nohp_pegawai);
        datepgw.setDateFormatString(ttl_pegawai);
       
    }//GEN-LAST:event_tblpegawaiMouseClicked

    private void namapegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapegawaiActionPerformed

    private void btnUpdate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate5ActionPerformed
        String id_pegawai = idpegawai.getText();
        execute.execpegawai eBook = new execute.execpegawai();
        int hasil = eBook.deletepegawai(id_pegawai);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDatapegawai();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnUpdate5ActionPerformed

    private void btnsimpanpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanpgActionPerformed
        String id_pegawai = idpegawai.getText();        
        String nama_pegawai= namapegawai.getText();
        String alamat_pegawai = alamatpegawai.getText();
        String nohp_pegawai = nohppegawai.getText();
        String ttl_pegawai = tanggal3;
        entity.pegawai pegawai = new entity.pegawai(id_pegawai, nama_pegawai, alamat_pegawai, nohp_pegawai,  ttl_pegawai);
        execute.execpegawai eBook = new execute.execpegawai();
        int hasil = eBook.insertpegawai(pegawai);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDatapegawai();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }        
    }//GEN-LAST:event_btnsimpanpgActionPerformed

    private void alamatdokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatdokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatdokterActionPerformed

    private void nohpdokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpdokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpdokterActionPerformed

    private void idpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpegawaiActionPerformed

    private void alamatpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatpegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatpegawaiActionPerformed

    private void nohppegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohppegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohppegawaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new login().setVisible(true);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardlaporan");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btncreatelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatelActionPerformed
        String id_laporan_penyakit = idlaporan.getText();        
        String id_pasien= ktp.getText();
        String iddokter = id_dokter.getText();
        String penyakitpasien = penyakit_pasien.getText();
        String obt = obat.getText();
        entity.laporanpenyakit laporanpenyakit = new entity.laporanpenyakit(id_laporan_penyakit, obt, iddokter, penyakitpasien, obt);
        execute.execlaporanpenyakit elaporan = new execute.execlaporanpenyakit();
        int hasil = elaporan.insertlaporanpenyakit(laporanpenyakit);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDatalaporanpenyakit();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }        
    }//GEN-LAST:event_btncreatelActionPerformed

    private void btnupdatelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatelActionPerformed
        String id_laporan_penyakit = idlaporan.getText();        
        String id_pasien= ktp.getText();
        String iddokter = id_dokter.getText();
        String penyakitpasien = penyakit_pasien.getText();
        String obt = obat.getText();
        entity.laporanpenyakit laporanpenyakit = new entity.laporanpenyakit(id_laporan_penyakit, obt, iddokter, penyakitpasien, obt);
        execute.execlaporanpenyakit elaporan = new execute.execlaporanpenyakit();
        int hasil = elaporan.updatelaporanpenyakit(laporanpenyakit);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDatalaporanpenyakit();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_btnupdatelActionPerformed

    private void btnhapuslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapuslActionPerformed
        String id_laporan = idlaporan.getText();
        execute.execlaporanpenyakit elaporan = new execute.execlaporanpenyakit();
        int hasil = elaporan.deletelaporanpenyakit(id_laporan);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDatalaporanpenyakit();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnhapuslActionPerformed

    private void tbllaporanpenyakitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllaporanpenyakitMouseClicked
        int row = tbllaporanpenyakit.getSelectedRow();
        String id_laporan_penyakit = tbllaporanpenyakit.getValueAt(row, 0).toString();
        String id_pasien = tbllaporanpenyakit.getValueAt(row, 1).toString();
        String iddokter = tbllaporanpenyakit.getValueAt(row, 2).toString();
        String penyakitpasien = tbllaporanpenyakit.getValueAt(row, 3).toString();
        String obt = tbllaporanpenyakit.getValueAt(row, 4).toString();
        idlaporan.setText(id_laporan_penyakit);
        ktp.setText(id_pasien);
        id_dokter.setText(iddokter);
        penyakit_pasien.setText(penyakitpasien);
        obat.setText(obt);
    }//GEN-LAST:event_tbllaporanpenyakitMouseClicked

    private void datepPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datepPropertyChange
        if (datep.getDate()!= null){
        SimpleDateFormat formattanggal = new SimpleDateFormat("yyyy-MM-dd");
        tanggal1 = formattanggal.format(datep.getDate());            
    }
    }//GEN-LAST:event_datepPropertyChange

    private void datedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datedPropertyChange
        if (dated.getDate()!= null){
        SimpleDateFormat formattanggal = new  SimpleDateFormat("yyyy-MM-dd");
        tanggal2 = formattanggal.format(dated.getDate());}
        
    }//GEN-LAST:event_datedPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardpelaporan");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void datepgwPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datepgwPropertyChange
        if (datepgw.getDate()!= null){
        SimpleDateFormat formattanggal = new  SimpleDateFormat("yyyy-MM-dd");
        tanggal3 = formattanggal.format(datepgw.getDate());}
    }//GEN-LAST:event_datepgwPropertyChange

    private void makebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makebtnActionPerformed
        new report().setVisible(true);
    }//GEN-LAST:event_makebtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int row = tblpelaporan.getSelectedRow();
        PrintJob p = getToolkit().getPrintJob(this,"Report",null);
        Graphics g = p.getGraphics();
        g.setFont(new Font("Serif",Font.BOLD,25));
        g.drawString("PELAPORAN UGD",100, 50);
        g.setFont(new Font("Serif",Font.PLAIN,12));
        g.drawString("ID Pelaporan : "+tblpelaporan.getValueAt(row, 0),100,100);
        g.drawString("ID laporan Penyakit : "+tblpelaporan.getValueAt(row, 1),100,130);
        g.drawString("Id Pegawai : "+tblpelaporan.getValueAt(row, 2),100,160);
        g.drawString("Tanggal pelaporan : "+tblpelaporan.getValueAt(row, 3),100,190);
        g.drawString("status : "+tblpelaporan.getValueAt(row, 4),100,220);
        g.setFont(new Font("Serif",Font.BOLD,12));
        g.setFont(new Font("Serif",Font.PLAIN,12));
        for (int i=0;i<tblpelaporan.getModel().getRowCount()-1;i++){
        }
        p.end();
        JOptionPane.showMessageDialog(rootPane,"Data Berhasil di Cetak");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setDatapelaporan();
        setDatadokter();
        setDatalaporanpenyakit();
        setDatapasien();
        setDatapegawai();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jScrollPane7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane7MouseClicked
    
    }//GEN-LAST:event_jScrollPane7MouseClicked

    private void tblpelaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpelaporanMouseClicked
        int row = tblpelaporan.getSelectedRow();
        String id_pelaporan = tblpelaporan.getValueAt(row, 0).toString();
        String id_laporan = tblpelaporan.getValueAt(row, 1).toString();
        String id_pegawai = tblpelaporan.getValueAt(row, 2).toString();
        String tanggal_pelaporan = tblpelaporan.getValueAt(row, 3).toString();
        String status = tblpelaporan.getValueAt(row, 4).toString();
        idpelaporan1.setText(id_pelaporan);
        idlaporan1.setText(id_laporan);
        idpegawai1.setText(id_pegawai);
        tanggal.setText(tanggal_pelaporan);
        status1.setText(status);
    }//GEN-LAST:event_tblpelaporanMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new report(idpelaporan1.getText(), idlaporan1.getText(), idpegawai1.getText(), tanggal.getText(), status1.getText()).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormStore().setVisible(true);
            }
        });
    }
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatdokter;
    private javax.swing.JTextField alamatpasien;
    private javax.swing.JTextField alamatpegawai;
    private javax.swing.JButton btnHapusp;
    private javax.swing.JButton btnSimpanp;
    private javax.swing.JButton btnUpdate5;
    private javax.swing.JButton btnUpdated;
    private javax.swing.JButton btnUpdatep;
    private javax.swing.JButton btnUpdatepg;
    private javax.swing.JButton btncreated;
    private javax.swing.JButton btncreatel;
    private javax.swing.JButton btndeletepu;
    private javax.swing.JButton btndokter;
    private javax.swing.JButton btnhapusd;
    private javax.swing.JButton btnhapusl;
    private javax.swing.JButton btnpasien;
    private javax.swing.JButton btnpegawai;
    private javax.swing.JButton btnsimpanpg;
    private javax.swing.JButton btnupdatel;
    private com.toedter.calendar.JDateChooser dated;
    private com.toedter.calendar.JDateChooser datep;
    private com.toedter.calendar.JDateChooser datepgw;
    private javax.swing.JTextField gejalapasien;
    private javax.swing.JTextField id_dokter;
    private javax.swing.JTextField iddokter;
    private javax.swing.JTextField idlaporan;
    private javax.swing.JTextField idlaporan1;
    private javax.swing.JTextField idpasien;
    private javax.swing.JTextField idpegawai;
    private javax.swing.JTextField idpegawai1;
    private javax.swing.JTextField idpelaporan1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField ktp;
    private javax.swing.JButton makebtn;
    private javax.swing.JTextField namadokter;
    private javax.swing.JTextField namapasien;
    private javax.swing.JTextField namapegawai;
    private javax.swing.JTextField nohpdokter;
    private javax.swing.JTextField nohppasien;
    private javax.swing.JTextField nohppegawai;
    private javax.swing.JTextField obat;
    private javax.swing.JTextField penyakit_pasien;
    private javax.swing.JPanel pnlInputBuku;
    private javax.swing.JPanel pnlTblBuku;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JPanel pnldokter;
    private javax.swing.JPanel pnllaporan;
    private javax.swing.JPanel pnlpasien;
    private javax.swing.JPanel pnlpegawai;
    private javax.swing.JPanel pnlpelaporan;
    private javax.swing.JTextField status1;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTable tbldokter;
    private javax.swing.JTable tbllaporanpenyakit;
    private javax.swing.JTable tblpasien;
    private javax.swing.JTable tblpegawai;
    private javax.swing.JTable tblpelaporan;
    // End of variables declaration//GEN-END:variables


}
