/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import entity.convertclasstoobject;
import main.MainFormStore;
import entity.pelaporanugd;
import execute.execpelaporanugd;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.print.PrinterException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import javax.swing.JTable.PrintMode;

/**
 *
 * @author Hafizh
 */
public class report extends javax.swing.JFrame {
String tanggal;
    /**
     * Creates new form report
     */
    public report() {
        initComponents();

    }
     public report(String idpelaporan, String idlaporan, String idpegawai, String tanggalpelaporan, String Status) {
        initComponents();
        this.idlaporan.setText(idlaporan);
        this.idpelaporan.setText(idpelaporan);
        this.idpegawai.setText(idpegawai);
        this.datepu.setDateFormatString(tanggalpelaporan);
        this.status.setSelectedItem(Status);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlpelaporan = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btncreatepelaporan = new javax.swing.JButton();
        btnupdatepelaporan = new javax.swing.JButton();
        idpelaporan = new javax.swing.JTextField();
        idlaporan = new javax.swing.JTextField();
        idpegawai = new javax.swing.JTextField();
        datepu = new com.toedter.calendar.JDateChooser();
        status = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel26.setText("Input Data Pelaporan UGD");

        jLabel27.setText("id_pelaporan_ugd");

        jLabel28.setText("id_Pegawai");

        jLabel29.setText("id_laporan_penyakit");

        jLabel30.setText("tanggal_pelaporan");

        jLabel31.setText("Status");

        btncreatepelaporan.setText("Create");
        btncreatepelaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatepelaporanActionPerformed(evt);
            }
        });

        btnupdatepelaporan.setText("Update");
        btnupdatepelaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatepelaporanActionPerformed(evt);
            }
        });

        datepu.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datepuPropertyChange(evt);
            }
        });

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dirawat", "Pulang", "Dipindahkan" }));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlpelaporanLayout = new javax.swing.GroupLayout(pnlpelaporan);
        pnlpelaporan.setLayout(pnlpelaporanLayout);
        pnlpelaporanLayout.setHorizontalGroup(
            pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpelaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                        .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlpelaporanLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(69, 69, 69)
                                .addComponent(idpelaporan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlpelaporanLayout.createSequentialGroup()
                                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30)
                                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(btncreatepelaporan)))
                                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(datepu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idlaporan)
                                            .addComponent(idpegawai)
                                            .addComponent(status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btnupdatepelaporan)
                                        .addGap(57, 57, 57)
                                        .addComponent(jButton1)))))
                        .addContainerGap(51, Short.MAX_VALUE))))
        );
        pnlpelaporanLayout.setVerticalGroup(
            pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpelaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                        .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlpelaporanLayout.createSequentialGroup()
                                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlpelaporanLayout.createSequentialGroup()
                                        .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel27)
                                            .addComponent(idpelaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel29))
                                    .addComponent(idlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idpegawai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel30))
                            .addComponent(datepu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel31))
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlpelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncreatepelaporan)
                    .addComponent(btnupdatepelaporan)
                    .addComponent(jButton1))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlpelaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlpelaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncreatepelaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatepelaporanActionPerformed
        String id_pelaporan = idpelaporan.getText();        
        String id_laporan = idlaporan.getText();
        String id_pegawai = idpegawai.getText();
        String tanggal_pelaporan = tanggal;
        String stat = (String) status.getSelectedItem();
        entity.pelaporanugd pelaporanugd = new entity.pelaporanugd(id_pelaporan, id_laporan, id_pegawai, tanggal_pelaporan, stat);
        execute.execpelaporanugd epelaporan = new execute.execpelaporanugd();
        int hasil = epelaporan.insertpelaporanugd(pelaporanugd);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }  
        Reset();
        this.dispose();
 
    }//GEN-LAST:event_btncreatepelaporanActionPerformed
    private void Reset() {
        idlaporan.setText("");
        idpegawai.setText("");
        idpelaporan.setText("");
    }
    private void datepuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datepuPropertyChange
        if (datepu.getDate()!= null){
        SimpleDateFormat formattanggal = new  SimpleDateFormat("yyyy-MM-dd");
        tanggal = formattanggal.format(datepu.getDate());}
    }//GEN-LAST:event_datepuPropertyChange

    private void btnupdatepelaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatepelaporanActionPerformed
        String id_pelaporan = idpelaporan.getText();        
        String id_laporan = idlaporan.getText();
        String id_pegawai = idpegawai.getText();
        String tanggal_pelaporan = tanggal;
        String stat = (String) status.getSelectedItem();
        entity.pelaporanugd pelaporanugd = new entity.pelaporanugd(id_pelaporan, id_laporan, id_pegawai, tanggal_pelaporan, stat);
        execute.execpelaporanugd epelaporan = new execute.execpelaporanugd();
        int hasil = epelaporan.updatepelaporanugd(pelaporanugd);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
        Reset();
        this.dispose();
    }//GEN-LAST:event_btnupdatepelaporanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreatepelaporan;
    private javax.swing.JButton btnupdatepelaporan;
    private com.toedter.calendar.JDateChooser datepu;
    private javax.swing.JTextField idlaporan;
    private javax.swing.JTextField idpegawai;
    private javax.swing.JTextField idpelaporan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel pnlpelaporan;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
